# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB, InfluxDB-writer and Grafana services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

volumes:
  mainflux-influxdb-volume:
  mainflux-grafana-volume:

services:
  influxdb:
    image: influxdb:2.0.8
    container_name: mainflux-influxdb
    restart: on-failure
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_BUCKET: ${MF_INFLUXDB_DB_BUCKET}
      DOCKER_INFLUXDB_INIT_USERNAME: ${MF_INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${MF_INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${MF_INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${MF_INFLUXDB_ADMIN_TOKEN}

    networks:
      - matrinos-network
    ports:
      - ${MF_INFLUXDB_PORT}:${MF_INFLUXDB_PORT}
    # command: sh -c 'sleep 10 && influx v1 auth create --read-bucket mainflux --write-bucket mainflux --username mainflux --password mainflux --org mainflux-org && influx v1 auth set-active --username mainflux'
    volumes:
      - mainflux-influxdb-volume-v2:/var/lib/influxdb
      - ./config:/etc/influxdb

  influxdb-writer:
    image: matrinos/influxdb-writer:${MF_RELEASE_TAG}
    container_name: mainflux-influxdb-writer
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      MF_INFLUX_WRITER_LOG_LEVEL: debug
      MF_NATS_URL: ${MF_NATS_URL}
      MF_INFLUX_WRITER_PORT: ${MF_INFLUX_WRITER_PORT}
      MF_INFLUX_WRITER_BATCH_SIZE: ${MF_INFLUX_WRITER_BATCH_SIZE}
      MF_INFLUX_WRITER_BATCH_TIMEOUT: ${MF_INFLUX_WRITER_BATCH_TIMEOUT}
      MF_INFLUXDB_DB: ${MF_INFLUXDB_DB}
      MF_INFLUX_WRITER_DB_HOST: ${MF_INFLUXDB_DB}
      MF_INFLUXDB_PORT: ${MF_INFLUXDB_PORT}
      MF_INFLUXDB_ADMIN_USER: ${MF_INFLUXDB_ADMIN_USER}
      MF_INFLUXDB_ADMIN_PASSWORD: ${MF_INFLUXDB_ADMIN_PASSWORD}
      MF_INFLUX_WRITER_TRANSFORMER: ${MF_INFLUX_WRITER_TRANSFORMER}
      MF_INFLUXDB_ADMIN_TOKEN: ${MF_INFLUXDB_ADMIN_TOKEN}
      MF_INFLUXDB_ORG: ${MF_INFLUXDB_ORG}
      MF_INFLUXDB_BUCKET: ${MF_INFLUXDB_DB_BUCKET}
      MF_API_KEY: ${MF_API_KEY}
      MF_URL: ${MF_URL}
    ports:
      - ${MF_INFLUX_WRITER_PORT}:${MF_INFLUX_WRITER_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ./config.toml:/config.toml

  grafana:
    image: grafana/grafana:7.3.7
    container_name: mainflux-grafana
    depends_on:
      - influxdb
    restart: on-failure
    ports:
      - ${MF_INFLUX_WRITER_GRAFANA_PORT}:${MF_GRAFANA_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - mainflux-grafana-volume:/var/lib/grafana
